num_cs = 40
init_soc_frac = 0.2
avail = 300

t_bound = 15 # hours
step_size = 1e-3
tol_error = 1e-6

energy_price = 0.05 # â‚¬/kWh

arr_prob = 1e-4
dep_prob = 1e-6

[coeff]
alpha.max = 1
alpha.min = 0.9
epsilon.max = 0.2
epsilon.min = 0.1
eta.max = 1
eta.min = 0.99
gamma.max = 0.15
gamma.min = 0.05
mu.max = 0.5
mu.min = 0.01
sigma.max = 0.9
sigma.min = 0.1



